/* COUNTRIES */ 
INSERT INTO public.countries (name) VALUES ('USA');
INSERT INTO public.countries (name) VALUES ('Great Britain');
INSERT INTO public.countries (name) VALUES ('France');
INSERT INTO public.countries (name) VALUES ('UAE');
INSERT INTO public.countries (name) VALUES ('Mexico');
INSERT INTO public.countries (name) VALUES ('Bali');
INSERT INTO public.countries (name) VALUES ('Singapore');
INSERT INTO public.countries (name) VALUES ('Thailand');
INSERT INTO public.countries (name) VALUES ('Egypt');
INSERT INTO public.countries (name) VALUES ('Turkey');

/* TRANSPORT */
INSERT INTO public.transport (name) VALUES ('Bus');
INSERT INTO public.transport (name) VALUES ('Airplane');
INSERT INTO public.transport (name) VALUES ('Train');
INSERT INTO public.transport (name) VALUES ('Cruise');

/* AGENCIES */
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Solo Travel', '+380678760382', 'Starokyivska Str 7, Kyiv 04116', 2);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Super Tour', '+380939823781', 'Spasska Str 20, Kyiv 04726', 4);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Good Bye My Little Friend', '+380447630923', 'Kharkivska Str 81, Kyiv 04982', 1);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('One way ticket', '+380449830293', 'Telihy Str 12, Kyiv 04983', 4);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Wow Travel', '+380639872673', 'Khreshatyk Str 58, Kyiv 04832', 2);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Around the World', '+380960129834', 'Bulgakova bld. 6/А, Kyiv 04032', 5);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Burning tours', '+380442510312', 'Peremohi Pr., bld. 125, Kyiv 04932', 1);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Best cruises', '+380449873201', 'Soborna Str, 26, appt. 7, Kyiv 04075', 6);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('Come with us', '+380985567382', 'Solomenska Str, 11/А, Kyiv 04060', 3);
INSERT INTO public.agencies (name, phone, address, years) VALUES ('East-West', '+380502930132', 'Dragomanova Str, 14, Kyiv 04892', 8);

/* AGENCIES_TO_TRANSPORT */
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (1, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (1, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (2, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (2, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (2, 4);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (3, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (3, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (4, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (5, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (6, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (6, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (6, 3);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (6, 4);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (7, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (7, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (8, 4);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (9, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (9, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (9, 3);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (10, 1);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (10, 2);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (10, 3);
INSERT INTO public.agencies_to_transport (agency_id, transport_id) VALUES (10, 4);

/* TOURS */
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 1', 1050, 5, '2021-05-02 17:25:00.000000', 1);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 2', 495, 3, '2021-04-05 16:30:00.000000', 1);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 3', 480, 4, '2021-04-10 16:45:00.000000', 1);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 4', 600, 5, '2021-04-15 07:15:00.000000', 2);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 5', 630, 3, '2021-04-17 09:00:00.000000', 2);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 6', 1050, 7, '2021-04-19 08:30:00.000000', 3);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 7', 540, 4, '2021-04-19 07:45:00.000000', 3);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 8', 1485, 9, '2021-04-21 12:00:00.000000', 3);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 9', 1800, 12, '2021-04-23 10:10:00.000000', 3);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 10', 1050, 7, '2021-04-23 20:30:00.000000', 4);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 11', 1050, 5, '2021-05-25 11:45:45.000000', 5);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 12', 960, 8, '2021-04-25 08:40:00.000000', 5);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 13', 1365, 7, '2021-04-27 10:00:00.000000', 5);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 14', 675, 5, '2021-05-01 06:30:00.000000', 6);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 15', 1200, 10, '2021-05-01 05:15:00.000000', 6);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 16', 2880, 16, '2021-05-03 12:30:00.000000', 7);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 17', 1320, 8, '2021-05-03 08:00:00.000000', 7);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 18', 975, 5, '2021-05-04 23:20:00.000000', 7);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 19', 1650, 10, '2021-05-06 14:20:00.000000', 7);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 20', 2160, 12, '2021-05-06 10:30:00.000000', 8);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 21', 1440, 8, '2021-05-08 09:00:00.000000', 8);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 22', 1350, 10, '2021-05-08 16:30:00.000000', 9);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 23', 1050, 7, '2021-05-09 17:50:00.000000', 9);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 24', 825, 5, '2021-05-12 18:15:00.000000', 9);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 25', 540, 4, '2021-05-24 19:15:00.000000', 9);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 26', 1050, 7, '2021-05-05 17:10:00.000000', 10);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 27', 1650, 10, '2021-05-08 08:10:00.000000', 10);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 28', 675, 5, '2021-05-01 12:30:00.000000', 4);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 29', 1155, 7, '2021-05-28 20:45:00.000000', 2);
INSERT INTO public.tours (id, name, amount, duration, departure, agency_id) VALUES (default, 'Tour 30', 945, 7, '2021-05-05 07:15:00.000000', 1);

/* TOURS TO COUNTRIES */
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (1, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (2, 4);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (2, 2);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (3, 6);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (4, 5);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (4, 3);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (4, 10);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (5, 5);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (6, 3);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (7, 2);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (8, 2);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (8, 8);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (9, 9);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (9, 4);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (9, 3);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (9, 5);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (10, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (10, 2);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (10, 5);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (11, 3);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (12, 10);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (12, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (13, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (14, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (14, 8);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (14, 10);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (15, 7);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (15, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (16, 4);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (17, 10);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (17, 2);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (18, 5);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (19, 4);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (20, 7);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (20, 4);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (21, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (22, 2);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (23, 10);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (24, 8);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (25, 9);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (25, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (25, 3);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (26, 6);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (27, 7);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (27, 5);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (27, 1);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (28, 7);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (29, 3);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (30, 4);
INSERT INTO public.tours_to_countries (tour_id, country_id) VALUES (30, 3);